# Generated by Django 5.1.7 on 2025-06-22 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bereaved_member_name', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=50)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('contribution', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact', models.CharField(max_length=20)),
                ('date_of_contribution', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBMS.case')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBMS.rank')),
            ],
        ),
    ]
