# Generated by Django 5.2.4 on 2025-07-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBMS', '0002_useractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='method',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='path',
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
