# Generated by Django 5.2.4 on 2025-07-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBMS', '0003_remove_useractivity_method_remove_useractivity_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(max_length=255),
        ),
    ]
