# Generated by Django 5.2.4 on 2025-07-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBMS', '0004_useractivity_ip_address_alter_useractivity_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='method',
            field=models.CharField(default='GET', max_length=10),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
