# Generated by Django 5.2.4 on 2025-07-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBMS', '0006_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('READ', 'Read')], max_length=10),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
