# Generated by Django 5.2.4 on 2025-08-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBMS', '0007_alter_auditlog_action_alter_auditlog_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='method',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useractivity',
            name='model_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useractivity',
            name='object_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
