# Generated by Django 5.2.4 on 2025-08-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBMS', '0008_remove_useractivity_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
