# Generated by Django 5.2.4 on 2025-09-14 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBMS', '0010_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='contribution',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('view', 'View'), ('export', 'Export'), ('backup', 'Backup'), ('force_logout', 'Force Logout'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='CaseAccountability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('contribution', 'Contribution'), ('expense', 'Expense')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountability', to='DBMS.case')),
            ],
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
