# Generated by Django 5.2.4 on 2025-09-15 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBMS', '0013_expenditure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expenditure',
        ),
    ]
