# Generated by Django 5.2.4 on 2025-09-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBMS', '0015_expenditure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='date',
            field=models.DateField(),
        ),
    ]
