# Generated by Django 5.2.4 on 2025-09-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBMS', '0016_alter_expenditure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
